name: 'hello'
version: 0.0.1
description: A web server built using the redstone package.
#author: Robert Åkerblom-Andersson <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
  redstone: '>=0.6.0 <0.7.0'

